# Generated by Django 5.2.17 on 2026-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeywordStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized", models.CharField(max_length=100, unique=True)),
                ("keyword", models.CharField(max_length=100)),
                ("pc_searches", models.PositiveIntegerField(default=0)),
                ("mobile_searches", models.PositiveIntegerField(default=0)),
                ("pc_under_10", models.BooleanField(default=False)),
                ("mobile_under_10", models.BooleanField(default=False)),
                ("pc_clicks", models.FloatField(default=0)),
                ("mobile_clicks", models.FloatField(default=0)),
                ("pc_ctr", models.FloatField(default=0)),
                ("mobile_ctr", models.FloatField(default=0)),
                ("competition", models.CharField(blank=True, max_length=10)),
                ("ad_depth", models.FloatField(default=0)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-mobile_searches"],
            },
        ),
        migrations.CreateModel(
            name="ApiCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("key", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key"), name="unique_api_cache_entry"
                    )
                ],
            },
        ),
    ]
