# Generated by Django 5.2.17 on 2026-09-27 15:03

from django.db import migrations, models


def drop_shared_cache(apps, schema_editor):
    # Rows cached before per-user scoping were fetched with server-wide keys.
    apps.get_model("research", "ApiCache").objects.filter(scope="").delete()
    apps.get_model("research", "KeywordStat").objects.filter(scope="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apicache",
            name="unique_api_cache_entry",
        ),
        migrations.AddField(
            model_name="apicache",
            name="scope",
            field=models.CharField(db_index=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="keywordstat",
            name="scope",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="keywordstat",
            name="normalized",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="apicache",
            constraint=models.UniqueConstraint(
                fields=("scope", "kind", "key"), name="unique_api_cache_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="keywordstat",
            constraint=models.UniqueConstraint(
                fields=("scope", "normalized"), name="unique_keyword_stat"
            ),
        ),
        migrations.RunPython(drop_shared_cache, migrations.RunPython.noop),
    ]
