# Generated by Django 5.2.17 on 2026-09-27 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("naver", "네이버 스마트스토어"), ("coupang", "쿠팡")],
                        default="naver",
                        max_length=20,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Internal name for the product", max_length=200
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="상품명 shown on the marketplace",
                        max_length=200,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("target_keywords", models.JSONField(blank=True, default=list)),
                ("category_path", models.CharField(blank=True, max_length=300)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "detail_page",
                    models.JSONField(
                        blank=True, default=dict, help_text="상세페이지 section spec"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DetailPageRender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec", models.JSONField()),
                ("html", models.TextField()),
                (
                    "images",
                    models.JSONField(
                        default=list, help_text="Paths relative to MEDIA_ROOT"
                    ),
                ),
                ("height", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renders",
                        to="listings.listingdraft",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
