# Generated by Django 5.2.17 on 2026-09-27 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("naver_searchad", "네이버 검색광고 API"),
                            ("naver_openapi", "네이버 개발자센터 API"),
                            ("llm", "AI 모델"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("secret_blob", models.TextField(blank=True)),
                ("hint", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("untested", "테스트 전"),
                            ("ok", "연결됨"),
                            ("error", "오류"),
                        ],
                        default="untested",
                        max_length=10,
                    ),
                ),
                ("status_message", models.CharField(blank=True, max_length=300)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "kind"), name="one_credential_per_kind"
                    )
                ],
            },
        ),
    ]
