# Generated by Django 5.2.17 on 2026-09-27 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("naver", "네이버 스마트스토어"), ("coupang", "쿠팡")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "파일 업로드"),
                            ("api", "API 연동"),
                            ("demo", "데모 데이터"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["marketplace", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KeywordInflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("keyword", models.CharField(max_length=100)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("orders", models.PositiveIntegerField(default=0)),
                ("revenue", models.BigIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_inflows",
                        to="store.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sales", "판매 실적"),
                            ("traffic", "방문 통계"),
                            ("keywords", "유입 키워드"),
                            ("ads", "광고 성과"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("rows", models.PositiveIntegerField(default=0)),
                ("first_date", models.DateField(blank=True, null=True)),
                ("last_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("visits", models.PositiveIntegerField(default=0)),
                ("page_views", models.PositiveIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic",
                        to="store.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("orders", models.PositiveIntegerField(default=0)),
                ("units", models.PositiveIntegerField(default=0)),
                ("revenue", models.BigIntegerField(default=0, help_text="KRW")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="store.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="store.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("keyword", models.CharField(blank=True, max_length=100)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("spend", models.BigIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("revenue", models.BigIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="store.store",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                fields=("owner", "marketplace", "name"), name="unique_store_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="unique_product_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="keywordinflow",
            constraint=models.UniqueConstraint(
                fields=("store", "date", "keyword"), name="unique_keyword_inflow"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailytraffic",
            constraint=models.UniqueConstraint(
                fields=("store", "date"), name="unique_daily_traffic"
            ),
        ),
        migrations.AddIndex(
            model_name="dailysales",
            index=models.Index(
                fields=["store", "date"], name="store_daily_store_i_6ca5e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailysales",
            constraint=models.UniqueConstraint(
                fields=("store", "product", "date"), name="unique_daily_sales"
            ),
        ),
        migrations.AddConstraint(
            model_name="addaily",
            constraint=models.UniqueConstraint(
                fields=("store", "date", "keyword"), name="unique_ad_daily"
            ),
        ),
    ]
